apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vaa2lb0qh-python 
  janus-idp.io/tekton: vaa2lb0qh-python
  backstage.io/kubernetes-id: vaa2lb0qh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vaa2lb0qh-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  