apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vaa2lb0qh-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vaa2lb0qh-python 
  name: vaa2lb0qh-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vaa2lb0qh-python 
